name: Fetch News via OpenAI

on:
  workflow_dispatch:
  schedule:
    # 매일 08:00 KST 실행 (UTC 기준 23:00 전날)
    - cron: '0 23 * * *'

permissions:
  contents: write

concurrency:
  group: fetch-news
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install openai requests beautifulsoup4

      - name: Run collector
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          # DEMO_MODE: '1'  # 네이버 키가 없으면 주석 해제하여 데모 실행
        run: |
          python scripts/collect_news.py

      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/*.json
          git commit -m "chore: update news data" || echo "no changes"
          git push
